USE DB_JEWELSITE

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORIES 
FOREIGN KEY (cid) REFERENCES CATEGORIES (cid) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE USERS
ADD CONSTRAINT FK_USER_ACCOUNT_TYPE
FOREIGN KEY (acid) REFERENCES ACCOUNT_TYPE (id) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE TEMP_USER_ORDERS
ADD CONSTRAINT FK_TEMP_USER_ORDERS_PRODUCT
FOREIGN KEY (pid) REFERENCES PRODUCT (pid) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE USER_ORDERS
ADD CONSTRAINT FK_USER_ORDERS_USER
FOREIGN KEY (uid) REFERENCES USERS (uid) ON DELETE CASCADE ON UPDATE CASCADE

ALTER TABLE USER_ORDERS
ADD CONSTRAINT FK_USER_ORDERS_PRODUCT
FOREIGN KEY (pid) REFERENCES PRODUCT (pid) ON DELETE CASCADE ON UPDATE CASCADE